bundler_args: ""
cache: bundler
sudo: false
branches:
  only: [master]
script: "bundle exec rake spec"
gemfile:
  - gemfiles/rails23.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
matrix:
  exclude:
    - rvm: 2.0
      gemfile: gemfiles/rails23.gemfile
    - rvm: 2.1.2
      gemfile: gemfiles/rails23.gemfile
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
